load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    sha256 = "b58cb7547a28b2c718d1e38aee18a3659c9e3ff52440297e965f5edffe34b6d0",
    build_file = "@//:gtest.BUILD",
    strip_prefix = "googletest-release-1.7.0"
)

http_archive(
    name = "gmock",
    url = "https://github.com/google/googlemock/archive/release-1.7.0.zip",
    sha256 = "407992e9ef17a08339cd383c33dbaff923969cfa01f8e4ceaeea679400016d85",
    build_file = "@//:gmock.BUILD",
    strip_prefix = "googlemock-release-1.7.0"
)

http_archive(
  name = 'emscripten_toolchain',
  url = 'https://github.com/kripken/emscripten/archive/1.37.22.tar.gz',
  build_file = '//:emscripten-toolchain.BUILD',
  strip_prefix = "emscripten-1.37.22",
)

http_archive(
  name = 'emscripten_clang',
  url = 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_64bit/emscripten-llvm-e1.37.22.tar.gz',
  build_file = '//:emscripten-clang.BUILD',
  strip_prefix = "emscripten-llvm-e1.37.22",
)